name: Hello

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi
        run: echo "Hello GitHub Actions 🚀"
      - name: show date and directory
        run: |
          date
          pwd
